name: Homework Validation and Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-tests-hash-and-execute:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Compute tests file hash
        id: check
        run: |
          HASH=$(shasum -a 256 cypress/e2e/spec.cy.js | awk '{ print $1 }')
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Verify tests integrity
        run: |
          EXPECTED_HASH="58f563f0a870daf29d28aaac5d2eb5cf5eef04093d70bb3853958deeaa465ba9"
          if [[ "${{ steps.check.outputs.hash }}" != "$EXPECTED_HASH" ]]; then
            echo "🚫 TEST FILE HAS BEEN MODIFIED. HASH CHECK FAILED!"
            exit 1
          else
            echo "✅ Test file integrity verified."
          fi

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests
        run: |
          npm run build
          npm run cy:run

      - name: Merge Mochawesome JSON Results
        if: always()
        run: |
          npx mochawesome-merge cypress/results/*.json > cypress/results/output.json

      - name: Obtain OIDC Token and Send detailed test results
        if: always()
        env:
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
        run: |
          ID_TOKEN=$(curl -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=homework-test-server" | jq -r '.value')

          TEST_RESULTS=$(cat cypress/results/output.json | jq '.')

          curl -X POST https://express-server-test-nz06tj0vu-michalqws-projects.vercel.app/api/results \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $ID_TOKEN" \
            -d @- <<EOF
          {
            "studentRepository": "${{ github.repository }}",
            "commitSha": "${{ github.sha }}",
            "testResult": $TEST_RESULTS
          }
          EOF